// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RangoAgil.API.DbContexts;

#nullable disable

namespace RangoAgil.API.Migrations
{
    [DbContext(typeof(RangoDbContext))]
    partial class RangoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("IngredienteRango", b =>
                {
                    b.Property<int>("IngredientesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RangosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientesId", "RangosId");

                    b.HasIndex("RangosId");

                    b.ToTable("IngredienteRango");

                    b.HasData(
                        new
                        {
                            IngredientesId = 1,
                            RangosId = 1
                        },
                        new
                        {
                            IngredientesId = 2,
                            RangosId = 1
                        },
                        new
                        {
                            IngredientesId = 3,
                            RangosId = 1
                        },
                        new
                        {
                            IngredientesId = 4,
                            RangosId = 1
                        },
                        new
                        {
                            IngredientesId = 5,
                            RangosId = 1
                        },
                        new
                        {
                            IngredientesId = 6,
                            RangosId = 1
                        });
                });

            modelBuilder.Entity("RangoAgil.API.Entities.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Carne de Vaca"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Cebola"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Alho"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Arroz"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Feijão"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Farofa"
                        });
                });

            modelBuilder.Entity("RangoAgil.API.Entities.Rango", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rangos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Vaca atolada"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Bife com Fritas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Strogonoff de carne"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Escondidinho de carne"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Bife a Cavala"
                        });
                });

            modelBuilder.Entity("IngredienteRango", b =>
                {
                    b.HasOne("RangoAgil.API.Entities.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RangoAgil.API.Entities.Rango", null)
                        .WithMany()
                        .HasForeignKey("RangosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
